### DISCUSSION TITLE
Tracking automatically generated parameters

### DISCUSSION THREAD

**Discussion by 371258** [treeverse/dvc#10248] [Help] [answered]
We are currently facing an issue with logging of parameters in DVC Live. Our project structure is shown below:

├───src
├───dvclive
│   └───plots
│   └───metrics.json
├───dvc.yaml
├───params.yaml

DVC Version: 3.39.0

We manually modify _params.yaml_ to set parameters for running experiments. This file mainly includes parameters that 
adapt data clearing. It does not include any hyperparameters of our model, because those are 
defined automatically using [Optunas ](https://optuna.readthedocs.io/en/stable/) hyperparameter tuning.  Nevertheless, we would like to log and track the hyperparameters found by Optuna. 

What is the recommended way to do this? 

We tried the following:

```
    with Live() as live:
        live.log_params(model.get_params())
```
		
While debugging we can see that the expected file is created in _dvclive/params.yaml_. But the file is removed automatically 
once the DVC pipeline finished. 

Any help is highly appreciated.

**Comment by dberenbaum** [comment]
Could you share the repo, or `dvc.yaml` structure, and/or code, as well as the versions of dvc and dvclive you are using? It's not clear why the `dvclive/params.yaml` is being removed when the pipeline finishes.

**Comment by 371258** [comment]
Hi @dberenbaum , 

some further information:

**DVC version**: 3.39.0
**DVCLive version**: 3.5.1

**dvc.yaml**

```
vars:
- raw_data: data/raw/data.csv
- cleared_data: data/processed/cleared.csv
- train_data: data/processed/train.csv
- test_data: data/processed/test.csv
- scaler: data/processed/scaler.bin
- model: models/model.sav

stages:
  clear:
    cmd: python src/clear.py --RAW_DATA=${raw_data}
    deps:
    - src/clear.py
    - ${raw_data}
    params:
    - shared
    - clear
    outs:
    - ${cleared_data}
  prepare:
    cmd: python src/prepare.py --CLEARED_DATA=${cleared_data}
    deps:
    - src/prepare.py
    - ${cleared_data}
    params:
    - shared
    - prepare
    outs:
    - ${train_data}
    - ${test_data}
    - ${scaler}
  train:
    cmd: python src/train.py --TRAIN_DATA=${train_data} --TEST_DATA=${test_data}
    deps:
    - src/train.py
    - ${train_data}
    - ${test_data}
    params:
    - shared
    - train
    outs:
    - ${model}
    - dvclive/optuna.db
  evaluate:
    cmd: python src/evaluate.py --MODEL=${model} --TEST_DATA=${test_data}
    deps:
    - src/evaluate.py
    - ${model}
    - ${test_data}
    params:
    - shared
    - evaluate

params:
- params.yaml
```

Script for training stage (**train.py**)  which is trying to log the model parameters (see line 27+28):

```
import joblib
import pandas as pd
import argparse
import os
import yaml
import xgboost as xgb
import optuna
from sklearn.metrics import recall_score, f1_score
from dvclive import Live

def train_model(train_data_path:str, test_data_path:str):
    
    // read train and test data
    // init x_train, y_train, x_test, y_test 

    hyperparams = tune_model_hyperparams(x_train, y_train, x_test, y_test)

    model = xgb.XGBClassifier()
    model.set_params(**hyperparams)
    model.fit(x_train, y_train)

    os.makedirs(os.path.join("models"), exist_ok=True)

    with open("models/model.sav", 'wb') as f:
        joblib.dump(model, f)

    with Live() as live:
        live.log_params(model.get_params())


def tune_model_hyperparams(x_train:pd.DataFrame, y_train:pd.DataFrame, x_test:pd.DataFrame, y_test:pd.DataFrame):
    optuna.logging.set_verbosity(optuna.logging.WARNING)

    def objective(trial):
        // Code for Optuna hyperparameter tuning objective
        return score

    study_name = "xgb-optuna-hyperparam-tuning"
    db_name = 'optuna.db'
    storage_name = f'sqlite:///dvclive/{db_name}'

    study = optuna.create_study(study_name=study_name, storage=storage_name, direction='maximize', load_if_exists=True)
    study.optimize(objective, n_trials=20)

    return study.best_params


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--TRAIN_DATA", default='data/processed/train.csv')
    parser.add_argument("--TEST_DATA", default='data/processed/test.csv')
    args = parser.parse_args()

    train_data_path = args.TRAIN_DATA
    test_data_path = args.TEST_DATA
    
    train_model(train_data_path, test_data_path)

if __name__ == "__main__":
    main()

```
