### DISCUSSION TITLE
Merge request approval workflow for data versioning

### DISCUSSION THREAD

**Discussion by pirnerjonas** [treeverse/dvc#9907] [New Features & Ideas]
Hi all,

I am wondering how you would implement a kind of merge request approval workflow for our dvc data repository.

Currently if we want to update the data in our s3 backend a developer does all the changes locally and pushes to the remote via `dvc push`. The developer can do something like a `dvc diff` or `dvc data status` to check the changes locally she is about to make but we are currently thinking how you would implement something like this in a CICD pipeline (we are using Gitlab).

> For our infrastructure projects managed via terraform and gitlab we can leverage merge request approval workflow / 4 eye principal within CICD pipelines e.g. like this:

```yaml

stages:
  - plan
  - deploy

plan_terraform:
  image:
    name: ...
  script:
    - terraform init -input=false
    - terraform plan -input=false 
  except:
    - master

deploy_terraform:
  image: ...
  script:
    - terraform init -input=false
    - terraform apply -input=false -auto-approve
  only:
    - master
```

> Via `terraform plan` you see the changes you are about to make but you don't carry them out. After reviewing and merging to `master` the changes would be applied to the cloud environment.

So ideally I would create a merge request that shows me the changes I am about to do to my data on s3 backend and only after I merge I would update the data.

### What I tried
When I tried working on this I realized that if I create a new data set version locally via dvc (change some files, `dvc commit`, `git commit` `.dvc` files, `git push`) and create a merge request I can get the data set diff between the two branches e.g. like this:

```yaml
...
data-check:
  stage: build
  image: ...
  before_script:
    - poetry install --only main
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - CURRENT_COMMIT=$(git rev-parse HEAD)
    - TARGET_COMMIT=$(git rev-parse origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
  script:
    - echo $CURRENT_COMMIT
    - echo $TARGET_COMMIT
    - poetry run dvc diff $TARGET_COMMIT $CURRENT_COMMIT --md -v --show-hash
  rules:
    - if: $CI_MERGE_REQUEST_IID
...
```
![image](https://github.com/iterative/dvc/assets/48887249/bfba1922-ec3f-494c-842f-cd19504a29a3)

But if I understood it correctly if I now want to do the `dvc push` in the CICD pipeline I would need access to the `.dvc/cache` folder which I out of the box don't have access to in my runner environment.

Maybe it is possible to share the cache locally and on the runner via a [shared cache](https://dvc.org/doc/user-guide/how-to/share-a-dvc-cache) but since I am currently struggeling with this I thought I raise the more general question about this setup here.

**Comment by shcheklein** [comment]
> So ideally I would create a merge request that shows me the changes I am about to do to my data on s3 backend and only after I merge I would update the data.

@pirnerjonas can we please explore this a bit more before we discuss some possible solutions?

I'm curious what do we even mean by "update the data".

- do you use a regular DVC remote or a [cloud versioned](https://dvc.org/doc/user-guide/data-management/cloud-versioning#cloud-versioning) one? 
- why is it not enough to always push data and approve metadata changes (`.dvc`, `dvc.lock`) in a MR / PR? You can still present some metrics, diff, etc (we can discuss that part also), but you won't need pushing any data on CI. Yes, clearly it means that you can have some extra data in your remote storage, etc - but you can always guarantee that those versions that got merged are staying there.

WDYT?

**Comment by pirnerjonas** [comment]
@shcheklein yes, certainly.

> do you use a regular DVC remote or a [cloud versioned](https://dvc.org/doc/user-guide/data-management/cloud-versioning#cloud-versioning) one?

We use Amazon S3 as dvc remote with `version_aware` flag enabled

> why is it not enough to always push data and approve metadata changes (.dvc, dvc.lock) in a MR / PR?

If I understand correctly the presented metrics in this MR / PR would then reflect **what already changed in the dataset** (so if a project is dependend on this data by e.g doing `dvc get` they would already cosume the updated data even though the MR / PR hasn't been approved). Maybe I should have also added that we want to use this repo as a kind of [data registry](https://dvc.org/doc/use-cases/data-registry).

So in general we want to establish some kind of review process (e.g. via MR / PR) for a new dataset version we are about to create because it will be used in production downstream applications (e.g. via `dvc get`). 

Hope this makes it a little bit clearer what we are trying to get to.

**Reply by shcheklein** [reply]
Yes, I understand. `version_aware` flag makes it less obvious, but in general with DVC (and especially data registry) you are relying on Git repo (a specific revision, let's say the main branch latest commit). So, metadata (in case of a `version_aware` remote `.dvc`, `dvc.lock` files have version ids to identify specific versions of the file).

Another way to put it. No matter how many updates people push, if you use `dvc get` and/or `dvc import` and/or `dvc pull` - you will be able to get the specific version from a particular commit.

Saying that, I understand that we would want to avoid creating extra layers of objects on the cloud storage, and may be keep it "clean" as much as possible.

In this case, the only way that comes to my mind is to use two remotes. One is setup in way that anyone could push to. On the CI job you push into the "golden" / "production" one. Would something like this work for you?

**Comment by pirnerjonas** [comment]
I also thought about this two remote setup before.. I tried to implement this approach however I currently have some problems with it:

.dvc/config
```
[core]
    autostage = true
['remote "remote-prod"']
    url = s3://dvcstore/prod
    version_aware = true
['remote "remote-dev"']
    url = s3://dvcstore/dev
    version_aware = true
```

I went ahead and pushed some of my local files to the --remote-dev by `dvc push --remote remote-dev` and I correctly see the files popping up in the s3 bucket location `s3://dvcstore/dev`. However after running the CICD pipeline (like below) the `s3://dvcstore/prod` stays empty even though the output in the CICD pipeline suggests otherwise.

.gitlab-ci.yml
```yaml
data-push:
  stage: deploy
  image: ...
  before_script:
    - poetry install --only main
  script:
    - poetry run dvc pull --remote remote-dev -v
    - poetry run dvc push --remote remote-prod -v
  needs: [authenticate]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```
![image](https://github.com/iterative/dvc/assets/48887249/b3d895cd-f376-4760-ad93-2295e3b9af6e)

Do you have an idea what I am doing wrong? Was this the setup you meant?
